### ISSUE TITLE
For 1 access on public file sharing, there is 2 alerts in left panel (pydio 6.3.1)

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1089] opened 2016-03-17 10:14 UTC
For 1 access on public file sharing, there is 2 alerts in left panel

![2016-03-17_110038](https://cloud.githubusercontent.com/assets/3939543/13842802/7ab7fd26-ec30-11e5-88e4-700b33529142.png)

same thing on email notification

![2016-03-17_110127](https://cloud.githubusercontent.com/assets/3939543/13842806/80464fd6-ec30-11e5-8d05-d1338010d307.png)

Works fine on public folder sharing

**Comment by cdujeu** [comment] 2016-03-17 18:22
can you confirm that with an image as well? I wonder if it's because opening the docs or the pdf did trigger a download, and thus trigger a second alert

**Comment by Ellega** [comment] 2016-03-17 18:33
I confirm the same with JPG files

**Comment by cdujeu** [comment] 2016-03-23 09:55
we won't fix that, it's over-complicated.

**Closed by cdujeu** 2016-03-23 09:55 UTC
Labels: 6.3.1 - DEV

**Comment by Ellega** [comment] 2016-03-23 10:20
Ok o_O 
But You must know that this bug appear with simple mail notification.
We receive 2 mail notification with different text for 1 sharing open ...

**first mail**

![2016-03-23_111041](https://cloud.githubusercontent.com/assets/3939543/13982197/d7e11a20-f0e8-11e5-96b8-3f91bdc797e9.png)

**second mail**

![2016-03-23_111106](https://cloud.githubusercontent.com/assets/3939543/13982201/dc736282-f0e8-11e5-8ee7-47da417273d5.png)

**Comment by cdujeu** [comment] 2016-03-23 10:31
yes, that's why we have introduced the "mail queue" anyway, to avoid receiving too many emails. So this should "fix" the issue :-)

**Comment by Ellega** [comment] 2016-03-23 18:41
Don't want launch yet discussion but
Notification number is importante for us. 
Not easy to explain this regression to users.

**Comment by cdujeu** [comment] 2016-03-23 18:44
... let's have a discussion then :-) For me it was not a regression, are you sure it is?

**Comment by Ellega** [comment] 2016-03-23 19:00
Because on the single file sharing, notification without preview is like number of download for them. 
It has a quick indicator  when they set the max number of download . :-)

**Comment by Ellega** [comment] 2016-03-23 20:07
I found somethings, all of this appear when preview is enable not if preview is disable.
You already know, I think 
All of this is strange for me.
Ok. I'm giving up :-) 
sorry for the noise

**Comment by cdujeu** [comment] 2016-03-24 06:33
No worries. The explanation is that there is one notif for the actual opening of the link, and one that is hooked to the fact that the specific file was opened in a previewer.

**Comment by cdujeu** [comment] 2016-03-24 06:35
@Ellega on another topic, can you kindly retest on IIS the various sharing features and the possible encoding issues? Like sharing inside an ééé folder, sharing a ééé.txt file, updating share label & description, etc... Thx!

**Comment by Ellega** [comment] 2016-03-24 10:18
I do that ASAP :-)

**Comment by Ellega** [comment] 2016-03-24 14:01
I tested every possibility with sharing feature.
no encoding issues detected :-)
(label, description, file name, folder name,after uploading, rename, ...)

**Comment by Ellega** [comment] 2016-03-24 15:30
In fact I have found issues with minsite if accent in path. :-/

**Comment by cdujeu** [comment] 2016-03-24 15:34
yep
