### ISSUE TITLE
Password reset button issues

### ISSUE THREAD

**Issue by JacobHonore** [pydio/pydio-core#885] opened 2015-03-27 11:02 UTC
There are general problems with the buttons when resetting a password.

When you have resetted your password you come to a box with the following text:
A reset password request has been sent to the email registered with your account. Click on the link in the email to recreate a password.
In this box you cannot click the tick-button (Which would make sense to redirect to frontpage)
The X button redirects to frontpage though.

When you have changed the password it comes up with a “Thank you, you can now log in!” text and 2 buttons. The tick-button does nothing and the X button just closes the sidepanel.

**Comment by cdujeu** [comment] 2015-03-30 10:29
the commit fixes the issues for me, but I could not reproduce the last one (X button closing side panel).

**Closed** 2015-03-30 10:29 UTC
Labels: component:gui, prio:normal, type:bug
