### ISSUE TITLE
API changes : Folder renaming drives the API to return uncomplete response

### ISSUE THREAD

**Issue by jabarkarim** [pydio/pydio-core#1029] opened 2015-12-31 15:57 UTC
```
Steps that lead to the issue:

1 - Create a folder with name1
2 - Perform some operations (create, delete...) on its content
3 - Rename folder (from name1 to name2 for example)
4 - Perform some operations (create, delete...) on its content
5 - Rename folder from name2 to name1
6 - Finally ask "changes" with the following parameters:
     * seq_id = 0
     * stream = true
     * filter = the actual folder path

Expected result :
      List of "create" that is the actual content of the folder
Observed result:
     * A list of "create" that is not the actual content of the folder
     * Some are missing
```

**Comment by cdujeu** [comment] 2016-01-02 10:37
Still can't reproduce that. What are the respective names you are using for folder / renamed folder? 
-c

**Comment by cdujeu** [comment] 2016-03-28 09:03
not reproduced yet. Closing for now.

**Closed by cdujeu** 2016-03-28 09:03 UTC
