### ISSUE TITLE
Share office documents with Zoho is impossible

### ISSUE THREAD

**Issue by anthony97400** [pydio/pydio-core#1039] opened 2016-01-19 21:10 UTC
Hello,

Im trying to share *.doc files with some other users, in order to get a collaborative document.

Without Zoho, i can share the file without any problem. 
The share link allows my friend to download the document file.
But, he cannot edit the file online.

So i activate Zoho (in order to allow modification online on the document), but the share link gives this error : “Cannot find file !”

My goal is to allow other users to see, and edit all documents files like word and excel files.
Thanks

**Comment by cdujeu** [comment] 2016-03-08 18:37
Hi can you send a link with a sample doc ? I cannot reproduce that currently.

**Comment by anthony97400** [comment] 2016-03-09 09:55
Hi Charles,

Here is an example shared link :
https://ze-cloud.com/data/public/test








And now, when we try to access to the link, we get this error message :

**Comment by cdujeu** [comment] 2016-03-11 15:31
Hello, 
Just to make sur, can you try with the latest dev build (6.3.1, just released) ? 
https://pydio.com/en/community/releases/pydio-core/pydio-core-631-development-release
Thx

**Comment by cdujeu** [comment] 2016-03-17 11:04
Hello @anthony97400 did you had a chance to test 6.3.1?
-c

**Comment by cdujeu** [comment] 2016-03-18 11:42
@anthony97400 this should be fixed in 6.3.1, please retest (see linked PR). Closing for now.

**Closed by cdujeu** 2016-03-18 11:42 UTC
Labels: status:not-reproduced

**Comment by anthony97400** [comment] 2016-03-19 05:49
Hello

im out of my office
I will make the test in 2 weeks
Sorry for the delay and thanks for your work
