### ISSUE TITLE
Watched status not honored on sharing pages

### ISSUE THREAD

**Issue by Flauschbaellchen** [pydio/pydio-core#832] opened 2015-02-12 07:36 UTC
After starting watching a file, I get notifications if someone opens/download the file directly within the portal.
However, if I share the file and then let an anonymous user open/download it, I get nothing.

Can anyone confirm it?

I'm currently running 6.0.2 and I know that there is already an update to 6.0.3.
But I didn't found anything mentioning something like that within the changelog.

Greetings~

**Comment by Ellega** [comment] 2015-02-12 09:56
Yes I confirm. But It is normal :-)
When you sharing a folder or a file you have another option to set  or not "Watched status".
this option is set "not watched" by default
There is a distinction between internal and external user.

**Comment by Flauschbaellchen** [comment] 2015-02-12 10:47
Oww, ok sorry, my fault.
As opening the thread again in the forum would be useless, I just want to ask two more questions related to this topic:

* I don't get an email, just the notification within the portal.
* Would it be possible to add the IP used for opening/downloading the shared link to the notification(/email)?

**Comment by cdujeu** [comment] 2015-02-13 13:53
notifs & no emails: must be a PHP config issue. Do you succeed in sending any email from the app (like share links invitations)? 
User IP: they are in the admin logs, but currently not in the notif. Not really straightforward to expand the notif templates...
Closing as it's not a bug

**Closed by cdujeu** 2015-02-13 13:53 UTC
